import { Database } from "lucide-react";
import { FaAws, FaJava } from "react-icons/fa6";
import {
  SiAnthropic,
  SiApacheairflow,
  SiApachekafka,
  SiApachespark,
  SiCplusplus,
  SiDatabricks,
  SiDocker,
  SiDuckdb,
  SiDvc,
  SiElasticsearch,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithubactions,
  SiGo,
  SiGooglecloud,
  SiGradio,
  SiGrafana,
  SiHuggingface,
  SiJavascript,
  SiJupyter,
  SiKeras,
  SiKubernetes,
  SiLangchain,
  SiLaravel,
  SiLinux,
  SiMlflow,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiNvidia,
  SiOnnx,
  SiOpencv,
  SiPandas,
  SiPhp,
  SiPolars,
  SiPostgresql,
  SiPrometheus,
  SiPython,
  SiPytorch,
  SiRay,
  SiReact,
  SiRedis,
  SiRos,
  SiRust,
  SiScikitlearn,
  SiSnowflake,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
  SiWeightsandbiases,
  SiYolo,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import type { Icon } from "./link-icons";

// Logos for common ML/AI tools, matched against the skill name in info.json.
// Server-only: used by the Skills section, so none of this ships to the browser.
const SKILLS: [RegExp, Icon][] = [
  [/^python/i, SiPython],
  [/^c\+\+/i, SiCplusplus],
  [/^go(lang)?$/i, SiGo],
  [/^typescript/i, SiTypescript],
  [/^javascript/i, SiJavascript],
  [/^java$/i, FaJava],
  [/^php$/i, SiPhp],
  [/^rust$/i, SiRust],
  [/^c#$/i, TbBrandCSharp],
  [/^(sql|nosql)$/i, Database],
  [/pytorch/i, SiPytorch],
  [/tensorflow/i, SiTensorflow],
  [/keras/i, SiKeras],
  [/scikit/i, SiScikitlearn],
  [/numpy/i, SiNumpy],
  [/pandas/i, SiPandas],
  [/polars/i, SiPolars],
  [/jupyter/i, SiJupyter],
  [/hugging ?face/i, SiHuggingface],
  [/langchain/i, SiLangchain],
  [/anthropic|claude/i, SiAnthropic],
  [/onnx/i, SiOnnx],
  [/tensorrt|cuda|nvidia|triton/i, SiNvidia],
  [/opencv/i, SiOpencv],
  [/^yolo/i, SiYolo],
  [/^ros\b/i, SiRos],
  [/docker/i, SiDocker],
  [/kubernetes|k8s/i, SiKubernetes],
  [/^ray\b/i, SiRay],
  [/mlflow/i, SiMlflow],
  [/airflow/i, SiApacheairflow],
  [/weights ?& ?biases|wandb/i, SiWeightsandbiases],
  [/^dvc$/i, SiDvc],
  [/terraform/i, SiTerraform],
  [/prometheus/i, SiPrometheus],
  [/grafana/i, SiGrafana],
  [/github actions/i, SiGithubactions],
  [/^git$/i, SiGit],
  [/linux/i, SiLinux],
  [/^aws|amazon web services|sagemaker/i, FaAws],
  [/^gcp|google cloud|vertex/i, SiGooglecloud],
  [/spark/i, SiApachespark],
  [/kafka/i, SiApachekafka],
  [/databricks/i, SiDatabricks],
  [/snowflake/i, SiSnowflake],
  [/postgres/i, SiPostgresql],
  [/mysql/i, SiMysql],
  [/mongo/i, SiMongodb],
  [/redis/i, SiRedis],
  [/elasticsearch/i, SiElasticsearch],
  [/duckdb/i, SiDuckdb],
  [/fastapi/i, SiFastapi],
  [/streamlit/i, SiStreamlit],
  [/gradio/i, SiGradio],
  [/^react$/i, SiReact],
  [/^next\.?js/i, SiNextdotjs],
  [/^node(\.?js)?$/i, SiNodedotjs],
  [/^flask$/i, SiFlask],
  [/laravel/i, SiLaravel],
  [/tailwind/i, SiTailwindcss],
];

/** Logo for a skill, or null when there isn't a well-known one. */
export function skillIcon(name: string): Icon | null {
  return SKILLS.find(([pattern]) => pattern.test(name.trim()))?.[1] ?? null;
}
